version: '2'

services:
  database: 
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - .:/var/lib/redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - connect
  
  app:
    links:
      - database
    build: ./
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env 
    depends_on:
      - database
    command: ["${CMD}"]
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - PORT =${PORT}
    networks:
      - connect


networks:
  connect: 
