def result= false
pipeline {
    agent any
    stages {
        stage('Test') {
            steps{
                script {
                    withEnv(["CMD=tests/test.py", "PORT=20000"]){
                        result=sh(script: "docker-compose up", returnStatus: true)== 0
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    if (result){
                    withEnv(["CMD=hello.py", "PORT=20002"]){
                            sh( script:'docker-compose up -d')
                        }
                    }
                }
            }
        }
    }
}