def result= false
pipeline {
    agent any
    stages {
        stage('Test') {
            steps{
                script {
                    withEnv(["CMD=tests/test.py", "PORT=10000"]){
                        result = sh ( script: "docker-compose up -p test", returnStatus: true ) == 0
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    if (result){
                    withEnv(["CMD=hello.py", "PORT=10002"]){
                            sh ( script: "docker-compose up -d" )
                        }
                    }
                }
            }
        }
    }
}
