def result= false
pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                script{
                        sh(script:'docker-compose up -d')
                result = sh( script:'tests/test.py',returnStatus: true ) == 0
                }
            }
        }
        stage('Build') {
            when{
                expression { result }
            }
            steps {
                script{
                    sh( script:'docker-compose up -d')
                }
            }
        }
    }
}