version: '2'

services:
  web-server: 
    build: ./nginx 
    depends_on:
      - logstash
    ports:
      - 8080:8080
    networks:
      - connect

  logstash: 
    build: ./logstash
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000
    networks:
      - connect

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - myVol:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - connect
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks: 
      - connect


networks: 
  connect:
    driver: bridge

volumes:  
  myVol:
    driver: local  
